# services:
#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#
#   app:
#     build: .
#     container_name: analys_pro
#     restart: always
#     depends_on:
#       - db
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"
#
# volumes:
#   postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analys_pro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_HOST: host.docker.internal
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
